### ISSUE TITLE
Cannot read property 'set' of undefined - vue.JS

### ISSUE THREAD

**Issue by VAUNT** [froala/vue-froala-wysiwyg#116] opened 2019-09-24 12:51 UTC
Hello!

When on the page where I have many instance of froala, I found this error and the initialization of froala is very slow, need help! Thank you.

```
Uncaught TypeError: Cannot read property 'set' of undefined
    at htmlSet (vue-froala.js?86a1:111)
    at E.Bootstrap.eval (vue-froala.js?86a1:121)
    at E.Bootstrap.currentConfig.events.initialized (vue-froala.js?86a1:260)
    at Object.v [as trigger] (froala_editor.min.js?7ac3:7)
    at E.Bootstrap.S (froala_editor.min.js?7ac3:7)
```

the error is same here https://github.com/froala/vue-froala-wysiwyg/issues/111

the save is done correctly but the initialization is really slow

**Comment by yellow1912** [comment] 2019-10-27 03:20
I'm running into this exact issue. I wonder what is the problem here :(

**Comment by Centrallatice** [comment] 2019-10-27 11:00
I have the same issu too ...

**Comment by crx4** [comment] 2020-03-18 08:21
I have the same problem when I use multiple froala tag in a form.

**Comment by t0milee** [comment] 2020-04-15 16:24
@VAUNT any update on this?

**Comment by rcheung9** [comment] 2020-04-20 22:43
There have been multiple posts on this issue.  Wonder if this project is still being maintained?

**Comment by t0milee** [comment] 2020-04-21 15:01
Not really sure, last commits are from January, so not that long ago...

**Comment by crx4** [comment] 2020-04-25 18:56
If this repo was a third party I would ok with this situation. But it is official and still nothing happening about this, kinda sad...

**Comment by rcheung9** [comment] 2020-04-26 04:23
The saddest part is that we pay for a license and annual support but the devs don't even reply to a critical issue like this, for over half a year now.

**Comment by farena** [comment] 2020-10-30 11:38
I fix this issue with a v-if into the froala tag, i hope it helps someone

`<froala
        v-if="!loading"
        id="edit"
        v-model="resultHtml"
        :tag="'textarea'"
      />`

`data() {
    return {
      loading: true,
      resultHtml: null,
    };
  },
  mounted() {
    this.resultHtml = '<h1>Test</h1>';
    this.loading = false;
  },`

**Comment by drbarzaga** [comment] 2020-11-07 03:31
@farena  I try with your solution and this fixed my issue. Thanks!

**Comment by ilyaskarim** [comment] 2024-11-17 16:50
The issue is fixed in the following PR: https://github.com/froala/vue-froala-wysiwyg/pull/142

**Closed by ilyaskarim** 2024-11-17 16:50 UTC
