### ISSUE TITLE
styling lost when copy/pasting

### ISSUE THREAD

**Issue by nullest** [froala/vue-froala-wysiwyg#13] opened 2017-07-10 05:00 UTC
1.copy some text with style, eg:

`<p style="font-size: 18px; color: rgb(0, 128, 255);">It is blue.</p>`

2.paste it into my editor or even [https://www.froala.com/wysiwyg-editor](https://www.froala.com/wysiwyg-editor)

3.click "Code View", and it becomes:

`<p>It is blue.</p>`

--------------

I've tried: 

- [https://github.com/froala/wysiwyg-editor/issues/1386](url) 
- [https://github.com/froala/wysiwyg-editor/issues/1415](url) 

but it does not work.

**Comment by stefanneculai** [comment] 2017-07-10 09:20
Closing as duplicate of https://github.com/froala/wysiwyg-editor/issues/2083

**Closed by stefanneculai** 2017-07-10 09:20 UTC
